apiVersion: v1
kind: Service
metadata:
  name: emlauncher-web
  namespace: internal
  labels:
    name: emlauncher
#  annotations:
#    beta.cloud.google.com/backend-config: '{"ports": {"80":"emlauncher-backend-config"}}'
spec: 
  type: NodePort
  selector:
    app: emlauncher
    type: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emlauncher-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emlauncher
      type: web
  template:
    metadata:
      labels:
        app: emlauncher
        type: web
    spec:
      containers:
      - name: web
        image: "gcr.io/ateam-ent-tools/emlauncher-web:COMMIT_SHA"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports: 
          - containerPort: 80
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: emlauncher-web-cnf
        readinessProbe:
          httpGet:
            path: /healthcheck/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
